### PR TITLE
LOG-831. Add scripts to run SVT workload

### PR DESCRIPTION
**Pull request by jcantrill**
This PR
* Adds a script to run SVT workload to verify log throughput performance
* Updates the makefile

This test will allow us to verify no regressions are introduces when  swapping around configuration or component deployment

Ref: https://issues.redhat.com/browse/LOG-831

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @alanconway @vimalk78

**Comment by bparees** [comment]
non-shipping code changes, overriding bz

**Pull request merged**
