### PR TITLE
gofmted

### PR DESCRIPTION
**Pull request by josefkarasek**

### CODE REVIEW

**Comment by ewolinetz** [comment]
is there a way to configure `gofmt` to use spaces instead of tabs?

**Comment by josefkarasek** [comment]
@ewolinetz go uses tabs

Gofmt'd code is:
...
* uncontroversial: never have a debate about spacing or brace position ever again!

https://blog.golang.org/go-fmt-your-code

**Comment by josefkarasek** [comment]
To heat up the controversy... ;-)

https://github.com/golang/go/issues/16256#issuecomment-230173434

**Pull request merged**
