### PR TITLE
Bug 1782566. Allow legacy secure-forward regardless of LogForward being enabled

### PR DESCRIPTION
**Pull request by jcantrill**
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1782566

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @mburke5678 these changes will need to be updated in 4.3 documentation to reflect enabling secure-forwarding.  We'll have to advise:
* Where to alter the config for secure forward
* How to add certs to a specific secret

@anpingli we are pushing to get this into 4.3 once it merges.

**Comment by JAORMX** [comment]
```
 unable to recognize no matches for kind "OperatorGroup" in version "operators.coreos.com/v1alpha2"
```
huh

**Pull request merged**
