### PR TITLE
Bump operator-sdk to v1.20 & logerr to v2

### PR DESCRIPTION
**Pull request by btaani**
### Description
This PR:

1. Upgrades operator-sdk to v.1.20 (according to [this guide](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.20.0/))
2. Upgrades the `logerr` library to v2
3. Modifies the operator's source code to incorporate the new changes of `logerr`

 
### Links
- JIRA: [LOG-2520](https://issues.redhat.com/browse/LOG-2520) & [LOG-2521](https://issues.redhat.com/browse/LOG-2521)

### CODE REVIEW

**Comment by jcantrill** [comment]
/hold

@alanconway please review.  not sure how this may conflict your on going PR

**Comment by jcantrill** [comment]
@btaani please also remember to squash your commits before final merge

**Comment by btaani** [comment]
@jcantrill I left the commits for now to make it easier for reviewers to trace the changes between versions. I will squash them after the review of course! :)

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by btaani** [comment]
@alanconway I updated this PR by adding logerr v2 migration since it's tightly coupled with operator-sdk, we cannot divide them into two separate PRs in order for the ci tests to pass.
There are currently 2 commits, one for operator-sdk and the other for logerrv2. Once I get an approval here I'll squash them.

**Pull request merged**
