### PR TITLE
Bug 1799024: Enable legacy syslog support

### PR DESCRIPTION
**Pull request by jcantrill**
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1799024

@ahadas had to steal some of #356 to resolve this bug.

### CODE REVIEW

**Comment by jcantrill** [comment]
@mburke5678 This will be the change I was alluding too

**Comment by ahadas** [comment]
> @ahadas had to steal some of #356 to resolve this bug.

Sure :)
I've posted https://github.com/jcantrill/cluster-logging-operator/pull/2 that:
1. Makes some minor correction
2. Removes the secret related things as the current plugin doesn't support secure connection
3. May solve the failing e2e test

**Comment by jcantrill** [comment]
@ewolinetz squashed commits

**Comment by ahadas** [comment]
> @ewolinetz squashed commits

@jcantrill seems that we've lost the changes in jcantrill#2 in the process...

**Pull request merged**
