### PR TITLE
Bug 1803390: Fix typo in OutputConditionType

### PR DESCRIPTION
**Pull request by bmillemathias-1a**
Secet -> Secret.

### CODE REVIEW

**Comment by jcantrill** [comment]
@bmillemathias-1a thank you for the PR.  Please rebase to master and open bz as our merge workflow requires changes to be made in master branch and trickle down

**Comment by jcantrill** [comment]
please rebase against master.  backport workflow requires we start with master and work backwards

**Comment by jcantrill** [comment]
@https://github.com/bmillemathias-1a please rebase this against master.  i would expect there to be a single commit instead of multiple

**Comment by bmillemathias** [comment]
PR dropped in favor of #391

**Pull request closed without merging**
