### PR TITLE
Simplify structs used to pass in values from ConfigMaps or Secrets

### PR DESCRIPTION
**Pull request by xperimental**
### Description

This PR tries to simplify the structs used to pass ConfigMap or Secret values into the collector configuration by removing the additional nesting introduced by `LocalObjectReference`.

An example of the new usage:

```yaml
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: my-collector
  namespace: openshift-logging
spec:
  outputs:
  - name: lokistack-out
    type: lokiStack
    [...]
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
```

### CODE REVIEW

**Comment by xperimental** [comment]
Looking into the failures ... :mag:

**Comment by xperimental** [comment]
Missed a spot ... :roll_eyes:

**Review by alanconway — COMMENTED** [review]
/lgtm

**Pull request merged**
