### PR TITLE
LOG-4786: Label 'openshift.sequence' is missing when forwarding logs over syslog with vector

### PR DESCRIPTION
**Pull request by syedriko**
### Description

For vector forwarding to a syslog destination, generate the dedot transform that adds openshift.sequence to the log message.

/cc @cahartma 
/assign @jcantrill 

/cherry-pick release-5.8

### Links
- JIRA: https://issues.redhat.com/browse/LOG-4786

### CODE REVIEW

**Comment by jcantrill** [comment]
@syedriko this will do too much since it dedots the labels which is not reported as an issue.  That would be a regression which I'm concerned would introduce another bug.  What does fluentd do?  Does it dedot labels? cc @alanconway

**Comment by syedriko** [comment]
> @syedriko this will do too much since it dedots the labels which is not reported as an issue. That would be a regression which I'm concerned would introduce another bug. What does fluentd do? Does it dedot labels? cc @alanconway 

The transform that I added is exactly the same across the board, every output has it:
https://github.com/openshift/cluster-logging-operator/blob/d82c0ea89e177402d40312f4f009032f4088249b/internal/generator/vector/output/cloudwatch/cloudwatch.go#L86
https://github.com/openshift/cluster-logging-operator/blob/d82c0ea89e177402d40312f4f009032f4088249b/internal/generator/vector/output/gcl/gcl.go#L87
https://github.com/openshift/cluster-logging-operator/blob/d82c0ea89e177402d40312f4f009032f4088249b/internal/generator/vector/output/http/http.go#L126
https://github.com/openshift/cluster-logging-operator/blob/d82c0ea89e177402d40312f4f009032f4088249b/internal/generator/vector/output/kafka/kafka.go#L62
https://github.com/openshift/cluster-logging-operator/blob/d82c0ea89e177402d40312f4f009032f4088249b/internal/generator/vector/output/loki/loki.go#L122
https://github.com/openshift/cluster-logging-operator/blob/d82c0ea89e177402d40312f4f009032f4088249b/internal/generator/vector/output/splunk/splunk.go#L74

**Comment by jcantrill** [comment]
Answering my original question of what does fluentd do... the answer is yes, it also dedots for syslog

/approve
/lgtm

**Pull request merged**
