### PR TITLE
LOG-3176: refactor service reconciliation to get before create

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* refactors collector service reconciliation to try to get a service before trying to create
* Adds events to service reconciliation

### Links
* https://issues.redhat.com/browse/LOG-3176

### CODE REVIEW

**Comment by jcantrill** [comment]
@xperimental  what are the ramification regarding reconciliation should [this](https://github.com/openshift/cluster-logging-operator/pull/1699/files#diff-1818c9aa28f3c55ae37f836d02a88d112b48ef7a2401dff1f3f7262e47b8106cL97-R94) swallow the error and successful create everything else?  Since we are no longer periodically reconciling, does this mean we will not converge on creating the resources unless someone edits the CL instance or other event?  Should we be either returning the error or accumulating them?  Thoughts

**Review by cahartma — COMMENTED** [review]
/lgtm

**Pull request merged**
