### PR TITLE
Migrate to go modules

### PR DESCRIPTION
**Pull request by periklis**
### Motivation
This PR migrates dependency management from dep to go modules to enable forward versioned support for k8s >1.18 api, client-go, library-go. In addition the Makefile includes following enhancements:
- Pin `GOFLAGS` to `-mod=vendor` for vendoring all go module dependencies.

### CODE REVIEW

**Comment by jcantrill** [comment]
Leave hold in place until either we are comfortable landing LF GA in 4.5 or push to 4.6

**Comment by periklis** [comment]
@jcantrill This also need a last review please.

**Comment by alanconway** [comment]
/lgtm
I don't think this will cause any problems merging LF GA (I could be wrong) but I'll leave the hold for @jcantrill to remove in case I've missed something...

**Comment by jcantrill** [comment]
> /lgtm
> I don't think this will cause any problems merging LF GA (I could be wrong) but I'll leave the hold for @jcantrill to remove in case I've missed something...

In the interest of priorities, would prefer to land LF GA into master and know for certain

**Pull request merged**
