### PR TITLE
Revert "Bug 1915454: Enable deployment on OCP v4.6"

### PR DESCRIPTION
**Pull request by jcantrill**
This reverts commit 46dd7a6b0f888b79cd39f37c415272897f20c2d2.

cc @vimalk78 

ref https://bugzilla.redhat.com/show_bug.cgi?id=1915454

### CODE REVIEW

**Comment by jcantrill** [comment]
marking as a "valid" bug even though we are closing the issue and we do not require qe validation

**Review by vimalk78 — COMMENTED** [review]
/lgtm

**Review by vimalk78 — APPROVED** [review]

**Pull request merged**
