### PR TITLE
[release-5.7] LOG-3316: openshift-logging namespace can not be deleted

### PR DESCRIPTION
**Pull request by Clee2691**
### Description
This PR addresses the issue that deleting the `openshift-logging` namespace is prevented because the `ClusterLogging` instance has a finalizer that prevents its termination. This only happens when `Loki` is the log store type. 

The solution here is to just remove the addition of the finalizer.

Note: Known issue -> Orphan of some resources, namely the `ClusterRoles/ClusterRoleBindings` related to `Lokistack`

/cc @cahartma, @syedriko 
/assign @jcantrill 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-3316

### CODE REVIEW

**Comment by jcantrill** [comment]
/hold

@Clee2691 can you add a known issues readme or something in our docs describing this issue and the orphaned roles and bindings

**Comment by xperimental** [comment]
I think you can get rid of all the `appendFinalizer` / `removeFinalizer` code as well, they should be unused.

**Comment by Clee2691** [comment]
> can you add a known issues readme or something in our docs describing this issue and the orphaned roles and bindings

Added to the existing known issues document with the issue and related orphan resources.

> I think you can get rid of all the `appendFinalizer` / `removeFinalizer` code as well, they should be unused.

Removed. For future reference, the [controllerutil](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.0/pkg/controller/controllerutil) package actually has [AddFinalizer()](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.0/pkg/controller/controllerutil#AddFinalizer) and [RemoveFinalizer()](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.0/pkg/controller/controllerutil#RemoveFinalizer) functions.

**Pull request merged**
