### PR TITLE
LOG-1591: upgrade operator-sdk to the v1.2.0 - part 1

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### Description

- move `/controllers` to root dir
- remove `/pkg` dir
- use `sdk `1.2.0 to generate crd
- add kustomize, controller-gen to bingo

### Next step. Will be done in separate PR

- migrate Kubebuilder layout v2 to v3 
- remove operator SDK from go.mod
- remove ./hack/generate-crd script
- use "make bundle" to generate CSV and CRD files

/cc 
/assign @jcantrill  

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-1591
- Enhancement proposal:

### CODE REVIEW

**Comment by jcantrill** [comment]
@periklis please review.

**Review by periklis — APPROVED** [review]
LGTM

**Pull request merged**
