### PR TITLE
Bug 1884275: Revert CLF cluster scope

### PR DESCRIPTION
**Pull request by alanconway**
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1884275

/assign @jcantrill
/cc @periklis

### CODE REVIEW

**Comment by jcantrill** [comment]
@alanconway looks good but are there also changes needed to the "must-gather" bits now the resource is namespace?

**Comment by alanconway** [comment]
> @alanconway looks good but are there also changes needed to the "must-gather" bits now the resource is namespace?

Nope, I checked that and it looks like I never updated the must-gather scripts when I made the scope change in the first place :blush:

**Comment by alanconway** [comment]
/retest

e2e tests are passing on my local CRC cluster, suspect timeouts due to CI overload

**Pull request merged**
