### PR TITLE
LOG-1785: Modify e2e tests to deploy CLO once

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* modifies the e2e tests to deploy CLO once 
* removes the collector only test which relies on CLF (which we already test multiple times)

/hold

Ref: https://issues.redhat.com/browse/LOG-1785

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Review by alanconway — APPROVED** [review]
/lgtm

**Review by alanconway — COMMENTED** [review]
/lgtm

**Review by vimalk78 — APPROVED** [review]
/lgtm

**Pull request merged**
