### PR TITLE
Bug 1768474: Remove collector example from CSV

### PR DESCRIPTION
**Pull request by jcantrill**
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1768474

### CODE REVIEW

**Comment by JAORMX** [comment]
I think the patch needs to be rebased for it to pass CI.

**Comment by ewolinetz** [comment]
the test failed waiting for the CLO pod to be ready
```
         	wait_util.go:64: Waiting for full availability of cluster-logging-operator deployment (0/1)
        	clusterlogging_test.go:61: timed out waiting for the condition 
```

**Comment by ewolinetz** [comment]
once we fix the tests i'll add a `lgtm`

**Pull request merged**
