### PR TITLE
Fix pods log link

### PR DESCRIPTION
**Pull request by lukas-vlcek**
See https://jira.coreos.com/browse/LOG-452

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
Hold on with merging for now...

**Comment by lukas-vlcek** [comment]
@jcantrill If I squash will it keep attribution to @VladMasarik ? :-)

**Comment by jcantrill** [comment]
@lukas-vlcek I believe so... but if it does not... we will always know...

**Comment by ewolinetz** [comment]
/hold

@lukas-vlcek remove the hold when you're ready (`hold cancel`)

**Pull request merged**
