### PR TITLE
Update  proxy related variables from uppercase to lowercase inside unit test file `collector_test.go`

### PR DESCRIPTION
**Pull request by gmeghnag**
- To fix failed unit test of #1832

### Description

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:

### CODE REVIEW

**Comment by jcantrill** [comment]
@gmeghnag why would you not fix the tests as part of https://github.com/openshift/cluster-logging-operator/pull/1875 which is where they break?

**Comment by gmeghnag** [comment]
@jcantrill I thought a different PR was needed. 
So can you confirm that I can update PR #1875 and close this one?

**Comment by jcantrill** [comment]
@gmeghnag the tests fail in the other PR which means you need to fix them for those changes

**Comment by gmeghnag** [comment]
I updated PR #1832 with the unit test changes.

**Pull request closed without merging**
