### PR TITLE
LOG-3733: Checking on not nil given spec.Collection before migration

### PR DESCRIPTION
**Pull request by vparfonov**
### Description

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-3733
- Enhancement proposal:

### CODE REVIEW

**Review by jcantrill — CHANGES_REQUESTED** [review]
/approve
/hold

please add a test to support this change

**Comment by vparfonov** [comment]
> /approve /hold
> 
> please add a test to support this change

done

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm
/hold cancel

**Pull request merged**
