### PR TITLE
LOG-6487: Fix Kafka output Topic template 

### PR DESCRIPTION
**Pull request by vparfonov**
### Description
This PR addresses several mistakes in the Vector configuration generator templates. The initial issue was discovered in the Kafka output template, but further investigation revealed similar issues in other outputs, including `Cloudwatch`, `GoogleCloudLogging` and `ElasticSearch`.

In several places, a leading `.` (dot) was missing in field using. For example:

_Kafka_:
Incorrect:
```
topic = "{{ _internal.output_openshift_infra_logging_kafka_topic }}"
```
Correct:
```
topic = "{{ ._internal.output_openshift_infra_logging_kafka_topic }}"
```

_Cloudwatch_:
Incorrect: 
```
group_name = "{{ _internal.cw_group_name }}"
stream_name = "{{ stream_name }}"
```
Correct: 
```
group_name = "{{ ._internal.cw_group_name }}"
stream_name = "{{ .stream_name }}"
```
_ElasticSearch_:
Incorrect: 
```
bulk.index = "{{ _internal.es_1_index }}"
```
Correct: 
```
bulk.index = "{{ ._internal.es_1_index }}"
```

_GoogleCloudLogging_:
Incorrect: 
```
log_id = "{{ _internal.gcl_1_log_id }}"
```
Correct: 
```
log_id = "{{ ._internal.gcl_1_log_id }}"
```

/cc @cahartma @Clee2691 
/assign @jcantrill 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-6487
- Enhancement proposal:

### CODE REVIEW

**Comment by cahartma** [comment]
Within the templating syntax, the dot is inferred and not required.   I'm not certain about the others, but for sure CW is not broken and works as expected without the dot.

**Comment by vparfonov** [comment]
> Within the templating syntax, the dot is inferred and not required. I'm not certain about the others, but for sure CW is not broken and works as expected without the dot.

@cahartma Do you think these changes are useless?

**Comment by cahartma** [comment]
I see you closed it.   Let's chat in scrum today.   If you verified this fixes Kafka then we can still implement some sort of change to that specifically.

**Pull request closed without merging**
