### PR TITLE
LOG-4987: Deploy LokiStack read roles when console is active

### PR DESCRIPTION
**Pull request by xperimental**
### Description

This is a backport of #2306 to 5.8

/cc @periklis
/assign @jcantrill

### Links

- JIRA: [LOG-4987](https://issues.redhat.com//browse/LOG-4987)

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
/lgtm

**Comment by xperimental** [comment]
First thought: Everything fails pretty quick -> issue with CI ... but it turns out that this is incorrect. The (server-side) merge actually adds a compile error :slightly_smiling_face: 

Rebasing (so that I can do the merge myself) ...

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Pull request merged**
