### PR TITLE
LOG-955: Remove curator deployment

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
Curator is no longer required as it has been replaced by the retention policy.

This PR:
* Removes deployment of curator
* Cleans up existing curation deployment
* Adds CR status to identify deprecation of curator

/cc @igor-karpukhin @vimalk78 
/assign @ewolinetz @alanconway 

### Links
* https://issues.redhat.com/browse/LOG-955

This PR is likely blocked for 4.7 unless we can move logging to CPaaS in this timeframe

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
Manually merging into post branch as merge bot seems like its not doing its job :) All tests passed

**Pull request merged**
