### PR TITLE
Add license header for *.go files

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### Description
Add license header for *.go files

/cc 
/assign 

/cherry-pick

### CODE REVIEW

**Comment by jcantrill** [comment]
It would be awsome to have either a "pre-check" or linter that would wither fix files that don't have the license or fail the build

**Comment by vparfonov** [comment]
> It would be awsome to have either a "pre-check" or linter that would wither fix files that don't have the license or fail the build

will do

**Comment by blockloop** [comment]
The Apache 2.0 license does not require the header to exist on every source file, but "recommends" it. I think if we're not legally required to do this then we should avoid having to deal with it altogether.

**Pull request closed without merging**
