### PR TITLE
LOG-3280: exclude log generated by gateway and opa containers from loki stack

### PR DESCRIPTION
**Pull request by vparfonov**
### Description
This PR:
- excluded logs produced by containers from Loki stack and named "gateway" and "opa" 

/cc 
/assign @jcantrill 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Review by cahartma — COMMENTED** [review]
/lgtm

**Pull request merged**
