### PR TITLE
LOG-2869: Simplify sending audit-logs to LokiStack

### PR DESCRIPTION
**Pull request by xperimental**
### Description

This PR simplifies the configuration needed for forwarding audit-logs into LokiStack log store.

### Links

- JIRA: [LOG-2869](https://issues.redhat.com//browse/LOG-2869)

### CODE REVIEW

**Comment by xperimental** [comment]
/hold

This will conflict with #1578 , I'd suggest we try to get that one merged before. I have incorporated the changes from that PR into this one as well, so re-basing should be easy.

**Comment by xperimental** [comment]
/unhold

Rebase happened and all checks are happy now. :slightly_smiling_face:

**Comment by jcantrill** [comment]
/hold

I would like for us to review the API again.

**Pull request closed without merging**
