### PR TITLE
Remove targets for building custom bundles

### PR DESCRIPTION
**Pull request by xperimental**
### Description

Removes the make targets and supporting files for creating custom bundles using overlays.

@alanconway please have a look, maybe there's more unused parts that I missed.

### CODE REVIEW

**Comment by jcantrill** [comment]
@xperimental do we have alternate instructions to replace these?  @alanconway added these to satisfy a customer need to deploy release candidate or early releases.

**Comment by xperimental** [comment]
@jcantrill Alan requested to remove these after I added the `olm-*` targets. The new target are no direct replacement of these targets though, the removal is more for "general simplification".

**Comment by alanconway** [comment]
@jcantrill @xperimental these olm- targets are a perfectly good replacement for making "special" release bundle images, I already used them for the last HCP bundle. The are more self-explanatory than the old stuff since they don't require editing separate overlay config, just giving some parameters to make to control version & image destination.

**Review by alanconway — APPROVED** [review]

**Pull request merged**
