### PR TITLE
move the temp workdir as discussed for 1768042

### PR DESCRIPTION
**Pull request by jcantrill**
Asked to make the dir more obvious via chat in slack and discussed in https://bugzilla.redhat.com/show_bug.cgi?id=1768042#c8

### CODE REVIEW

**Comment by ewolinetz** [comment]
per the BZ, would it make more sense to instead make that error message more meaningful?
`"Operator unable to read local file to get contents: %v", err`

**Comment by jcantrill** [comment]
> per the BZ, would it make more sense to instead make that error message more meaningful?
> `"Operator unable to read local file to get contents: %v", err`

That would probably make it more obvious that its a local message.  Change is made in `util.go`?

**Comment by ewolinetz** [comment]
https://github.com/openshift/cluster-logging-operator/blob/master/pkg/utils/utils.go#L173

**Comment by jcantrill** [comment]
@ewolinetz updated to reflect the error message you suggested

**Pull request merged**
