### PR TITLE
Bug 1892511: Renamed level field in k8s/openshift audit logs

### PR DESCRIPTION
**Pull request by vimalk78**
### Description

Cherry pick of 8d0b1af270c9852dae1438da3dafb656f86ae1f9  (PR https://github.com/openshift/cluster-logging-operator/pull/815) onto release-4.6

/cc @jcantrill @igor-karpukhin 
/assign @jcantrill 

### Links
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1892511

### CODE REVIEW

**Comment by jcantrill** [comment]
blocker bug is in VERIFIED relabeling as valid

**Comment by wking** [comment]
Pulling in the severity label:

/bugzilla refresh

**Comment by mrunalp** [comment]
We need a valid bz cloned for this PR

**Pull request merged**
