### PR TITLE
LOG-1713: fix prometheus roles to be namespaced scoped

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Fixes the prometheus roles to be namespace scoped

### Links
* https://issues.redhat.com/browse/LOG-1713

### CODE REVIEW

**Comment by jcantrill** [comment]
> LGTM, but did you forget to generate the bundle maybe?

Ran make target but it appears it updated files outside of the changes I was targeting

**Review by periklis — COMMENTED** [review]
One more thing, you need to ensure that you manual delete the old clusterrole and clusterrolebinding from the bundle and manifests dir.

**Comment by jcantrill** [comment]
> One more thing, you need to ensure that you manual delete the old clusterrole and clusterrolebinding from the bundle and manifests dir.

@periklis I believe this change does accomplish removing those roles/bindings.  Existing deployments I do not believe will be updated to remove them.  I think this change also moves us one step closer to being able to remove the manifest directory

**Comment by periklis** [comment]
> > One more thing, you need to ensure that you manual delete the old clusterrole and clusterrolebinding from the bundle and manifests dir.
> 
> @periklis I believe this change does accomplish removing those roles/bindings. Existing deployments I do not believe will be updated to remove them. I think this change also moves us one step closer to being able to remove the manifest directory

Nope the `make bundle` command does not remove the ClusterRole and ClusterRoleBinding files at all. At the current SHA1 for this PR, the file still exists: https://github.com/openshift/cluster-logging-operator/blob/ba4354322a6be05457b25543af1752462bad2a24/bundle/manifests/cluster-logging-metadata-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml

**Comment by jcantrill** [comment]
> > > One more thing, you need to ensure that you manual delete the old clusterrole and clusterrolebinding from the bundle and manifests dir.
> > 
> > 
> > @periklis I believe this change does accomplish removing those roles/bindings. Existing deployments I do not believe will be updated to remove them. I think this change also moves us one step closer to being able to remove the manifest directory
> 
> Nope the `make bundle` command does not remove the ClusterRole and ClusterRoleBinding files at all. At the current SHA1 for this PR, the file still exists: https://github.com/openshift/cluster-logging-operator/blob/ba4354322a6be05457b25543af1752462bad2a24/bundle/manifests/cluster-logging-metadata-reader_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml

This is the role the collector uses to talk to the API server, not for prometheus to scrap the collector.  Interestingly though I wonder if we can reduce it to a namespaces role or if you require clusterwide in order to get pod meta from any pod across the cluster

**Pull request merged**
