### PR TITLE
Migrate E2E test check-logs from origin-aggregated-logging repo

### PR DESCRIPTION
**Pull request by periklis**

### CODE REVIEW

**Comment by jcantrill** [comment]
This looks alot like what I'm adding for my test https://github.com/openshift/cluster-logging-operator/pull/412 and does not seem to have a clear delineation between what LF tests already test and what my PR introduces

**Comment by periklis** [comment]
> This looks alot like what I'm adding for my test #412 and does not seem to have a clear delineation between what LF tests already test and what my PR introduces

Indeed #412 extends the checks for pod labels. We could merge the effort. However, this PR is separate of the LF tests in regard that it disables the LF annotation and checks for the log contents through es_util. Latter was the only big think in the old OAL test.

**Comment by periklis** [comment]
Close superseded by LF GA tests.

**Pull request closed without merging**
