### PR TITLE
Bug 1929420: ClusterLogForwarder with Output.Secret causes fluentd crash loop

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
The fix adds secrets during validation, changes the generate signature
and so touches a lot of files.

/cc @alanconway @vimalk78 

### Links
* 4.6 backport of https://github.com/openshift/cluster-logging-operator/pull/823
* Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1929420
* Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1929419

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Pull request merged**
