### PR TITLE
[release-4.5] Bug 1899419: Add keep-alive backend for elasticsearch store

### PR DESCRIPTION
**Pull request by periklis**
### Description
This is a manual backport of #760 

/cc @blockloop 
/assign @ewolinetz 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899419

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by jcantrill** [comment]
/hold

pending merge of https://github.com/openshift/origin-aggregated-logging/pull/2025

**Review by blockloop — CHANGES_REQUESTED** [review]
Indention is off on all of these changes.

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Pull request merged**
