### PR TITLE
Migrate operator-sdk and deps to v0.18.1

### PR DESCRIPTION
**Pull request by periklis**
### Motivation
Based on the [operator-sdk upgrade guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md) this PR updates the dependencies and adapts to breaking changes for operator-sdk@v0.18.1.

This PR enables the operator to use k8s v1.18.3 and in turn openshift release-4.6.

**Depends on:** #490, openshift/release#9883

### CODE REVIEW

**Comment by syedriko** [comment]
@periklis There's a good chance you're addressing https://bugzilla.redhat.com/show_bug.cgi?id=1849874 with this PR.

**Comment by syedriko** [comment]
@periklis Is this where the Operator SDK Version Upgrade Guide now lives: https://github.com/openshift/ocp-release-operator-sdk/blob/master/doc/migration/version-upgrade-guide.md ?

**Comment by periklis** [comment]
> @periklis Is this where the Operator SDK Version Upgrade Guide now lives: https://github.com/openshift/ocp-release-operator-sdk/blob/master/doc/migration/version-upgrade-guide.md ?

The official public available Migration reference is actually here: https://sdk.operatorframework.io/docs/migration/
The content seems to be the same with your link, but I would trust a public available source.

**Comment by periklis** [comment]
> @periklis There's a good chance you're addressing https://bugzilla.redhat.com/show_bug.cgi?id=1849874 with this PR.

Yes, skimming through operator-sdk issues/PRs I found one that matches the BZ description:
https://github.com/operator-framework/operator-sdk/pull/2210

**Comment by periklis** [comment]
> > @periklis There's a good chance you're addressing https://bugzilla.redhat.com/show_bug.cgi?id=1849874 with this PR.
> 
> Yes, skimming through operator-sdk issues/PRs I found one that matches the BZ description:
> [operator-framework/operator-sdk#2210](https://github.com/operator-framework/operator-sdk/pull/2210)

AH IC you did the hard work already: https://bugzilla.redhat.com/show_bug.cgi?id=1849874#c2

**Pull request merged**
