### PR TITLE
[release-4.6] Bug 1904380: Forwarding logs to Kafka using Chained certificates fails with error "state=error: certificate verify failed (unable to get local issuer certificate)

### PR DESCRIPTION
**Pull request by syedriko**
### Description

Manual cherrypick of https://github.com/openshift/cluster-logging-operator/pull/964 with minor supporting fixes.

- Upgraded Kafka to 2.7.0 and pushed images to quay.io
- Switched the kafka logforwarding test to run over TLS
- The Kafka broker certificate chain is Server - Intermediate CA - Root CA
- Added Java Key Store generation functions
- Removed Kafka consumer output to stdio to avoid recursive logs

/cc @vimalk78 
/assign @ewolinetz 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1904380

### CODE REVIEW

**Comment by syedriko** [comment]
cc @jcantrill

**Comment by sdodson** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*We've hit capacity of 50 for this week.*

* Score: *0.40*
* Reason: *maximum QE capacity for all z-stream is 50*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by jcantrill** [comment]
@sdodson please reconsider given this is an issue for logging

**Pull request merged**
