### PR TITLE
LOG-1500: Discard messages after 60m instead of retry forever

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Modifies buffer retry to drop log messages after 10 minutes
* Adds API to buffer tuning section to allow configuration of retry

/cc @alanconway 

### Links
* Ref: https://issues.redhat.com/browse/LOG-1500

### CODE REVIEW

**Review by alanconway — COMMENTED** [review]
This seems like a generic setting not a fluentd one. What do you think of putting it on the CLF output? We have a global outputDefaults field on the CLF now so you could still set a global default but also specific over-rides e.g. because an off-site output is expected to have more network problems than a local-store output.

**Comment by jcantrill** [comment]
> This seems like a generic setting not a fluentd one. What do you think of putting it on the CLF output? We have a global outputDefaults field on the CLF now so you could still set a global default but also specific over-rides e.g. because an off-site output is expected to have more network problems than a local-store output.

I agree this is a generic setting but I think the correct way to expose this is to roll it into a policy of some kind related to the buffer settings.  The "policy" would  spec the tradeoff regarding delivery guarantee and however we abstract file vs memory buffers.  I have mentioned this several times before and believe that would be a better approach.  The change here is more of a temporary fix.

Also, @sichvoge and I have talked about needing a more generic way to provide overrides which I need to discuss with you

**Pull request merged**
