### PR TITLE
Bug 2059996: Fix inability to tune read line limit when tuning buffers

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:

* fixes the issue where there is a mismatch between buffer tuning and in tail readline limit
* Introduces InTail tuning similar to Buffer tuning for fluentd
/assign @alanconway

### Links
* https://bugzilla.redhat.com/show_bug.cgi?id=2059996

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by anpingli** [comment]
label cherry-pick-approved

**Pull request merged**
