### PR TITLE
[release-4.3] Bug 1813381: addressing lf causing cert reconciliation

### PR DESCRIPTION
**Pull request by ewolinetz**
Manual cherry-pick of https://github.com/openshift/cluster-logging-operator/pull/323

To address https://bugzilla.redhat.com/show_bug.cgi?id=1813381

Dependent on https://github.com/openshift/cluster-logging-operator/pull/441 to fix failing tests

### CODE REVIEW

**Comment by anuj812** [comment]
While using Openshift 4.3.5, Cluster Logging Operator : Cluster logging Operator: 4.3.9-202003230345 , we starts getting below error after around 24 hours related to certificate and elastic search pods become down.  Is this also realted to this bug ?

{"level":"error","ts":1586146160.3927138,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"logforwarding-controller","request":"openshift-logging/instance","error":"Unable to create or update certificates for \"instance\": Error running script: exit status 1","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by periklis** [comment]
/retitle [release-4.3] Bug 1813381: addressing lf causing cert reconciliation

**Comment by crawford** [comment]
@ewolinetz the merge window has closed. The next patch manager will re-add the label once the window opens again. In the meantime, see if you can get CI fixed, since that is what ultimately prevented this from merging.

**Comment by ewolinetz** [comment]
this requires https://github.com/openshift/cluster-logging-operator/pull/441

**Comment by derekwaynecarr** [comment]
note 4/9: will revisit when team removes hold.

**Comment by ewolinetz** [comment]
> /hold to stop spinning

If this is on hold then the build manager will pass it over... 
https://github.com/openshift/cluster-logging-operator/pull/449#issuecomment-611574741

**Comment by eparis** [comment]
/lgtm cancel
please figure out why CI is failing (appears the build fails?

**Comment by russellb** [comment]
Hello, I'm patch-manager this week so I"m reviewing a bunch of backports.

In the future, could you provide more detail in the commit message?  The current commit message doesn't provide enough information to understand what the problem was and why these changes fix it.  That type of info would help when determining if it's an appropriate backport, and would also help others in the future reviewing history and trying to understand why changes were made.  Thanks!

**Pull request merged**
