### PR TITLE
LOG-1771: move runtime and builders out of test for larger reuse

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Refactors the `test/runtime` code into `internal/runtime` for reuse in our handlers
* Removes the `factory` package in favor of using builders and runtime

### Ref
* [LOG-1771](https://issues.redhat.com/browse/LOG-1771): Refactor test/runtime package into internal/runtime

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
closing in favor of https://github.com/openshift/cluster-logging-operator/pull/1202

**Pull request closed without merging**
