### PR TITLE
Updating deps to pull in latest ES cr change

### PR DESCRIPTION
**Pull request by ewolinetz**
/hold

### CODE REVIEW

**Comment by richm** [comment]
Are we ready to merge this or do we want to wait for https://github.com/openshift/elasticsearch-operator/pull/53 ?

**Comment by ewolinetz** [comment]
This is independent of that other PR, i believe it needs to go in before #98 though

**Comment by ewolinetz** [comment]
https://github.com/openshift/cluster-logging-operator/pull/101 should resolve the scc issue

**Pull request merged**
