### PR TITLE
LOG-1180: add docs to enable merge_json

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR adds documentation to describe how to enable merging of json logs in an unmanaged clusterlogging instance

### Links
Ref: https://issues.redhat.com/browse/LOG-1180

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @rolfedh @alanconway @sichvoge

**Comment by jcantrill** [comment]
cc @gkarager

**Comment by gkarager** [comment]
@jcantrill Is it possible to add more details about how to modify the fluentd config in 4.6? like, what to add/update in configmap/fluentd.

**Comment by sichvoge** [comment]
@jcantrill So is this specifically for 4.3 and 4.6? Is there anything to be said about the 4.6 ES data model like known issues or limitations (e.g. max field limits)?

**Comment by jcantrill** [comment]
> @jcantrill So is this specifically for 4.3 and 4.6? Is there anything to be said about the 4.6 ES data model like known issues or limitations (e.g. max field limits, what index you will find the logs, etc.)?

Nothing specific to the data model.  Is the link in the text sufficient? https://github.com/openshift/origin-aggregated-logging/issues/1492 ? or do we need more?

**Comment by gkarager** [comment]
Looks good to me.

**Comment by sichvoge** [comment]
Tested personally and I can see all fields that were part of the JSON message merged into the root of the final log record. LGTM.

**Review by lukas-vlcek — APPROVED** [review]
As for ES related changes: risks and issues are highlighted.

**Pull request merged**
