### PR TITLE
Update container registry to registry.ci.openshift.org

### PR DESCRIPTION
**Pull request by jcantrill**
### Description

This PR updates the container registry per dev email regarding the decommissioning of the other registry

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @vimalk78

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
/override ci/prow/e2e-operator

EventRouter test is broken and unrelated to issue

**Comment by jcantrill** [comment]
Follow up note: Only the eventrouter was failing in this test. need to review ASAP

**Pull request merged**
