### PR TITLE
Bug 1752073: Increased operator sdk version to 0.8.2

### PR DESCRIPTION
**Pull request by igor-karpukhin**
* Changed operator SDK version from 0.7.0 to 0.8.2
* Fixed `common.sh` script

### CODE REVIEW

**Comment by ewolinetz** [comment]
please be sure to squash your commits before we merge.
Now that the EO sdk bump has merged in we can probably update the deps again :)

**Comment by igor-karpukhin** [comment]
Do not merge yet, please. Gopkg toml not updated.

**Comment by ewolinetz** [comment]
/hold
it doesn't look like this pulled in the updated `elasticsearch-operator` changes... (looking at Gopkg.lock)

**Pull request merged**
