### PR TITLE
Bug 1873396: Move `lint` target to ensure it is run in CI

### PR DESCRIPTION
**Pull request by alanconway**
Move lint dependency from image: target to build:

The image target is not run during CI, build is.

Other misc. cleanup:

- Updated some Makefile comments
- Add explicit executable targets: bin/forwarder-generator, bin/cluster-logging-operator
- Remove unused code to download operator_sdk
- Removed Makefile 'bin' target: bingo, go build, get-openshift-client.sh create the dir.
- Fixed lint errors in collection.go and comparator_test.go

/cc @jcantrill
/cc @periklis

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by alanconway** [comment]
/retest
previous test job stuck for 2 hours, something up.

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by periklis** [comment]
/retitle Bug 1873396: Move `lint` target to ensure it is run in CI

**Pull request merged**
