### PR TITLE
    LOG-2489  Loki tenant configuration and defaults

### PR DESCRIPTION
**Pull request by alanconway**
Fixed fluentd behavior and tests.

/cc @vimalk78

### CODE REVIEW

**Comment by xperimental** [comment]
I'd suggest waiting for the merge of this until #1503 is merged to avoid introducing additional workarounds for the logger.

**Comment by alanconway** [comment]
Needs to be resolved after https://issues.redhat.com/browse/LOG-2740 - loki/lokistack distinction needs to be clarified.

**Comment by alanconway** [comment]
/close

This branch will be folded into https://issues.redhat.com/browse/LOG-2811

**Pull request closed without merging**
