### PR TITLE
LOG-2544: Add support for Elasticsearch v8 for fluentd

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Adds fluentd support for Elasticsearch 8
* Add functionality to functional framework to utilize secrets
* Allows fluentd to verify es version on startup which may lead to transient  error messages

### Links
* https://issues.redhat.com/browse/LOG-2544

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @vimalk78  these changes may be useful for you to add secrets to functional testing

**Review by cahartma — COMMENTED** [review]
/lgtm

**Pull request merged**
