### PR TITLE
Reverting dashboard changes from earlier PR(JIRA ticket LOG-1320)

### PR DESCRIPTION
**Pull request by ajaygupta978**
### Description
Tow charts has been added in OCP. These has been describe in  https://issues.redhat.com/browse/LOG-1165 and https://issues.redhat.com/browse/LOG-1269.  
These changes will be reversed in this PR.

/cc @jcantrill 
/assign @jcantrill 

- Depending on PR(s): 
- Bugzilla:
- Github issue: 
- JIRA: [LOG-1320](https://issues.redhat.com/browse/LOG-1320)
- Enhancement proposal:

### CODE REVIEW

**Comment by vimalk78** [comment]
please change the target branch to `release-5.1`

**Comment by ajaygupta978** [comment]
Dashboard-Upper half
Screenshot 2021-05-05 at 12 58 14 PM
Dashboard-Lower half
Screenshot 2021-05-05 at 12 58 44 PM

@jcantrill above screenshot shows changes are reverted now.

**Comment by ajaygupta978** [comment]
> please change the target branch to `release-5.1`

Thanks @vimalk78. I changed to `release-5.1`

**Pull request merged**
