### PR TITLE
Update version for release 5.9

### PR DESCRIPTION
**Pull request by vparfonov**
### Description
This PR:

Updates the master branch for the 5.9 release

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:

### CODE REVIEW

**Comment by xperimental** [comment]
This seems to be a duplicate of #2225?

**Comment by jcantrill** [comment]
closing in favor of #2225

**Pull request closed without merging**
