### PR TITLE
LOG-1834:Move PriorityClass to operator manifest

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### Description
Move PriorityClass to operator manifest 

/cc 
/assign @jcantrill 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-1834
- Enhancement proposal:

### CODE REVIEW

**Comment by jcantrill** [comment]
@vparfonov Can you test the upgrade scenario to see if there are any issues related to having an existing priorityclass and OLM trying to upgrade where its provided via manifest

**Comment by vparfonov** [comment]
> @vparfonov Can you test the upgrade scenario to see if there are any issues related to having an existing priorityclass and OLM trying to upgrade where its provided via manifest

@jcantrill I tested upgrade scenario and didn't see any issue PriorityClass was successfully updated by OLM. Here i add yamls before and after update: 

<details>
<summary>PriorityClass CLOv5.3</summary>

```YAML
kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: cluster-logging
  uid: 7b123267-e233-41ba-9719-016feb2f9095
  resourceVersion: '158406'
  generation: 1
  creationTimestamp: '2022-02-02T14:27:26Z'
  ownerReferences:
    - apiVersion: logging.openshift.io/v1
      kind: ClusterLogging
      name: instance
      uid: 71f6980f-7e90-469a-862b-de5df79eca13
      controller: true
  managedFields:
    - manager: cluster-logging-operator
      operation: Update
      apiVersion: scheduling.k8s.io/v1
      time: '2022-02-02T14:27:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:description': {}
        'f:metadata':
          'f:ownerReferences':
            .: {}
            'k:{"uid":"71f6980f-7e90-469a-862b-de5df79eca13"}':
              .: {}
              'f:apiVersion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:preemptionPolicy': {}
        'f:value': {}
value: 1000000
description: This priority class is for the Cluster-Logging Collector
preemptionPolicy: PreemptLowerPriority
```
</details>  

<details>
<summary>PriorityClass CLOv5.4(actually v5.5)</summary>
```YAML
kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: cluster-logging
  uid: 7b123267-e233-41ba-9719-016feb2f9095
  resourceVersion: '164640'
  generation: 1
  creationTimestamp: '2022-02-02T14:27:26Z'
  labels:
    olm.owner: clusterlogging.v5.4.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-logging
  managedFields:
    - manager: cluster-logging-operator
      operation: Update
      apiVersion: scheduling.k8s.io/v1
      time: '2022-02-02T14:27:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:description': {}
        'f:preemptionPolicy': {}
        'f:value': {}
    - manager: catalog
      operation: Update
      apiVersion: scheduling.k8s.io/v1
      time: '2022-02-02T14:40:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:olm.owner': {}
            'f:olm.owner.kind': {}
            'f:olm.owner.namespace': {}
value: 1000000
description: This priority class is for the Cluster-Logging Collector
preemptionPolicy: PreemptLowerPriority
```
</details>

**Pull request merged**
