### PR TITLE
Bug 1901096: Set forward heartbeat to none

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR
*  sets the fluentd forward heartbeat to "none" to avoid dns resolution issues from stopping the pod from starting
* Expands the functional framework to add visitors in order to test this issue
```
2020-11-23 20:26:38 +0000 [error]: unexpected error error_class=SocketError error="getaddrinfo: Name or service not known"
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:680:in `getaddrinfo'
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:680:in `resolve_dns!'
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:666:in `resolved_host'
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:516:in `validate_host_resolution!'
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:237:in `block in configure'
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:227:in `each'
  2020-11-23 20:26:38 +0000 [error]: /usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_forward.rb:227:in `configure'
```

/cc @vimalk78 @igor-karpukhin 
/assign @alanconway 

### Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1901096

### CODE REVIEW

**Review by alanconway — CHANGES_REQUESTED** [review]
Code looks OK but I don't understand the problem you're fixing. What do heartbeats have to do with DNS resolution?

**Comment by jcantrill** [comment]
> Code looks OK but I don't understand the problem you're fixing. What do heartbeats have to do with DNS resolution?

The plugin generates the referenced error while trying to ensure there is a connection with destination by way of a "heartbeat".  This will cause the pod initialization to fail completely because it is unable to resolve the destination

**Comment by alanconway** [comment]
> > Code looks OK but I don't understand the problem you're fixing. What do heartbeats have to do with DNS resolution?
> 
> The plugin generates the referenced error while trying to ensure there is a connection with destination by way of a "heartbeat". This will cause the pod initialization to fail completely because it is unable to resolve the destination

Right, but won't we it fail anyway it tries to connect?
I'm OK with this for now, I think we need to review how we handle & report errors from fluentd but that's another task.
/lgtm

**Pull request merged**
