### PR TITLE
1691444 node selectors

### PR DESCRIPTION
**Pull request by jcantrill**
This bug fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1691444

By adding node selectors for the operands

Last commit is the only one of interest

### CODE REVIEW

**Comment by jcantrill** [comment]
tests wont pass until merge of https://github.com/openshift/cluster-logging-operator/pull/124 and https://github.com/openshift/cluster-logging-operator/pull/123

**Comment by ewolinetz** [comment]
can we also add a test in here to verify that if we don't specify a node selector that it is still empty/nil? (verifying the current deployment use case)

**Comment by jcantrill** [comment]
> can we also add a test in here to verify that if we don't specify a node selector that it is still empty/nil? (verifying the current deployment use case)

Added

**Pull request merged**
