### PR TITLE
LOG-2156: update (primary) shards expression to (total # of) shards

### PR DESCRIPTION
**Pull request by nladha09**
### Description
---
This PR: Updates `es_cluster_shards_number` expr for the Openshift Logging dashboard (not the Logging / Elasticseach one) to showcase accurate value for "total number of" Elasticsearch shards as mentioned in the [documentation](https://docs.openshift.com/container-platform/4.9/logging/cluster-logging-dashboards.html) (_as opposed to the current value of "total primary shards"_).

Here is the version details :

~~~
$> oc get csv
NAME                                 DISPLAY                                          VERSION    REPLACES                             PHASE
elasticsearch-operator.5.3.5-20      OpenShift Elasticsearch Operator                 5.3.5-20   elasticsearch-operator.5.3.4-13      Succeeded
~~~

Using the values in an example : (e.g. `max(es_cluster_shards_number{cluster="elasticsearch",type="active"})` value = 13 & `max(es_cluster_shards_number{cluster="elasticsearch",type="active_primary"})` value = 11 )

I could start a fresh cluster from OpenTLC, like the Hands-On OpenShift 4.9 which is available now, and I would have the same behavior.

I would expect to see 13 because the [docs](https://docs.openshift.com/container-platform/4.9/logging/cluster-logging-dashboards.html) state : 

> Elastic Shards | The total number of Elasticsearch shards in the Elasticsearch instance. 

However, the value shown is 11.

**Also request backporting to 5.4 and 5.3 please**

/cc @shwetaap
/assign @jcantrill
/assign @periklis 

<br>
<br>

### Links
---
- [x] JIRA: [Dashboard for OpenShift Logging in WebConsole shows incorrect number of shards](https://issues.redhat.com/browse/LOG-2156) <-- linking this JIRA as upon upgrading to the latest instance and I can see this is now using `max` instead of `sum(sum by(instance)` . So this is great, however, still need to adjust `active_primary` to `active` for total shards in the Elasticsearch instance, **not** total _primary_ shards.
- [x] SLACK thread: [#forum-logging](https://coreos.slack.com/archives/CB3HXM2QK/p1648548203813369?thread_ts=1645215311.915799&cid=CB3HXM2QK)

### CODE REVIEW

**Comment by jcantrill** [comment]
closing.  fixed by https://github.com/openshift/cluster-logging-operator/pull/1304

**Comment by jcantrill** [comment]
yet to be released against https://issues.redhat.com/browse/LOG-2156 in 5.4 and backported to 5.3 https://issues.redhat.com/browse/LOG-2048

**Comment by nladha09** [comment]
@jcantrill - Thank you for reviewing and commenting! If I'm not mistaken, [#1304](https://github.com/openshift/cluster-logging-operator/pull/1304) doesn't remove the `_primary` label off of the expression which this change will take care of. [#1304](https://github.com/openshift/cluster-logging-operator/pull/1304) fixed using `max` instead of `sum(sum by(instance)` - which was also needed. We still need to adjust `active_primary` to `active` to accurately display _total shards_ in the Elasticsearch instance, **not** total _primary_ shards.

**Comment by jcantrill** [comment]
Closing as issue is closed against a separate PR

**Pull request closed without merging**
