### PR TITLE
bug 1693957. Partial revert of 1666674

### PR DESCRIPTION
**Pull request by jcantrill**
This PR fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1693957 by partially reverting https://bugzilla.redhat.com/show_bug.cgi?id=1666674

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @richm in case you see auth funny business

**Comment by richm** [comment]
> cc @richm in case you see auth funny business

won't know until this PR merges, the image gets published, and a logging CI runs

**Pull request merged**
