### PR TITLE
Updated HACKING.md with better pull secret instructions

### PR DESCRIPTION
**Pull request by alanconway**
- merged improved info from private hacking doc 
- hack/update_pull_secret.sh to automate pull secret updates
- trivial fmt and lint fixes

### CODE REVIEW

**Comment by alanconway** [comment]
@jcantrill  - doc change only copied some of your hacking dock back into the repo HACKING.md.

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Comment by jcantrill** [comment]
added valid-bug label as this is docs change only

**Pull request merged**
