### PR TITLE
LOG-1925: Fix cpu graph on dashboard

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR fixes the CPU dashboard graph:
* fixing the metrics
* correcting the container name for collectors

### Links
* https://issues.redhat.com/browse/LOG-1925

### CODE REVIEW

**Review by ajaygupta978 — COMMENTED** [review]
@jcantrill : Any specific reason to use irate instead of rate.  Based on the documentation it says 
"irate should only be used when graphing volatile, fast-moving counters. Use rate for alerts and slow-moving counters".

**Comment by jcantrill** [comment]
> @jcantrill : Any specific reason to use irate instead of rate. Based on the documentation it says "irate should only be used when graphing volatile, fast-moving counters. Use rate for alerts and slow-moving counters".

The only reason I could find is that "rate" doesn't exist; the graph is blank. The "rate" version wasn't even suggested as part of the auto-complete.  When changed to "rate" it provided a graph

**Pull request merged**
