### PR TITLE
LOG-4604: Add infrastructure annotations

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:

adds infrastructure annotations

### Links
#2285

### CODE REVIEW

**Comment by cahartma** [comment]
@jcantrill can you briefly explain the files in /overlays directory and it's purpose?

**Comment by jcantrill** [comment]
> @jcantrill can you briefly explain the files in /overlays directory and it's purpose?

It's for controlling the build of alternate bundles but in this instance is cruft unrelated to the PR.  I will correct

/hold

**Pull request merged**
