### PR TITLE
Updated ViaQ/logerr to latest

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
  Latest version of ViaQ/logerr writes ordered logs, and adds filename and line number to logs

/cc @blockloop @eranra 
/assign @eranra @jcantrill 

/cherry-pick

### CODE REVIEW

**Review by blockloop — APPROVED** [review]

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm

**Comment by jcantrill** [comment]
Manually merging into post branch as merge bot seems like its not doing its job :)

**Pull request merged**
