### PR TITLE
Bug 1882524: Fixed 4.6 manifests folder and bundle validation

### PR DESCRIPTION
**Pull request by vimalk78**
The CLO operator bundle container contained patch files. This leads to failures to push the Errata Advisory to stage.

 - removed logforwardings.crd.yaml from bundle/manifest which is not present in CSV
 - moved crd patches from manifests/4.6 (which is used by ART) to manifest/patches, and modified crd generation scripts to use these patch files

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Review by periklis — CHANGES_REQUESTED** [review]
Why doing this copy/remove of the patches and not a simple remove from the bundle dir like the logforwarding CRD?

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Pull request merged**
