### PR TITLE
LOG-3398: Apply TLSSecurityProfile settings to TLS listeners in log collectors

### PR DESCRIPTION
**Pull request by syedriko**
### Description
This PR passes TLS min version and ciphersuites from the TLSSecurityProfile to the log collectors and the log file metric exporter.
Depends on corresponding PRs in vector and log-file-metric-exporter repos.

/cc @alanconway 
/assign @jcantrill 

### Links
- Depending on PR(s): https://github.com/ViaQ/vector/pull/129, https://github.com/ViaQ/log-file-metric-exporter/pull/26
- JIRA: https://issues.redhat.com/browse/LOG-3398

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

I take it this is prometheus and fluetnd part, vector is yet to come?

**Comment by syedriko** [comment]
> /lgtm
> 
> I take it this is prometheus and fluetnd part, vector is yet to come?

The prometheus listener in vector is very much there, the CLO changes are under internal/generator/vector and the corresponding vector changes are in https://github.com/ViaQ/vector/pull/129.

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
