### PR TITLE
LOG-1482: Add support for sending logs to Google CLoud Logging

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
Added support for sending logs to Google Cloud Logging
 - Added gcl output in the vector conf generator
 - Added `googleCloudLogging` output type in the CLF api
 - Added unit tests

/cc @jcantrill @alanconway 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-1482

### CODE REVIEW

**Comment by vimalk78** [comment]
possibly blocked by https://github.com/openshift/cluster-logging-operator/pull/1609

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Review by alanconway — APPROVED** [review]
/lgtm

**Pull request merged**
