### PR TITLE
Merge master-post-release back into master.

### PR DESCRIPTION
**Pull request by alanconway**
Land the log forwarding GA API.

### CODE REVIEW

**Comment by ewolinetz** [comment]
/hold
before we merge this back can we make sure we have our 4.5 migration bugs sorted out? just being cautious -- it'll make it easier to get them verified so we can backport if we don't introduce any potential new issues

**Comment by alanconway** [comment]
@ewolinetz I'll let you /unhold when you are ready.

**Comment by alanconway** [comment]
Closing in favour of #571

**Pull request closed without merging**
