### PR TITLE
LOG-342:Move RBAC from cluster logging operators Go code into respective manifests

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### Description
Move RBAC from cluster logging operators Go code into respective manifests

> NOTE: Some other improvments will be introduced i the PR  #1240

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-342
- Enhancement proposal:

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Review by syedriko — CHANGES_REQUESTED** [review]
@vparfonov There's one more RBAC-related object that's created programmatically, I think we can move to a manifest, too: the `log-collector-scc` `SecurityContextConstraints`. It's created in
https://github.com/openshift/cluster-logging-operator/blob/master/internal/k8shandler/scc.go, which we can remove completely. NewSCC() is called from https://github.com/openshift/cluster-logging-operator/blob/master/internal/k8shandler/collection.go#L573-L578

**Comment by vparfonov** [comment]
> @vparfonov There's one more RBAC-related object that's created programmatically, I think we can move to a manifest, too: the `log-collector-scc` `SecurityContextConstraints`. It's created in [`master`/internal/k8shandler/scc.go](https://github.com/openshift/cluster-logging-operator/blob/master/internal/k8shandler/scc.go?rgh-link-date=2022-01-31T19%3A28%3A27Z), which we can remove completely. NewSCC() is called from [`master`/internal/k8shandler/collection.go#L573-L578](https://github.com/openshift/cluster-logging-operator/blob/master/internal/k8shandler/collection.go?rgh-link-date=2022-01-31T19%3A28%3A27Z#L573-L578)

@syedriko I also thought about that but OLM not operate with object like `SecurityContextConstraints`, https://olm.operatorframework.io/docs/concepts/olm-architecture/.

**Comment by syedriko** [comment]
> @syedriko I also thought about that but OLM not operate with object like `SecurityContextConstraints`, https://olm.operatorframework.io/docs/concepts/olm-architecture/.

Seems like an omission on their part, but hey. Now thinking about it, before I added that code I tried creating this SCC from a manifest and it didn't work. Ship it! :)

**Pull request merged**
