### PR TITLE
Bug 1884477: Update bundle manifests for namespaced CLF

### PR DESCRIPTION
**Pull request by periklis**
### Description
This PR addresses the missing update of the bundle manifests after reverting CLF from cluster-scoped  to namespace-scoped. This is mandatory to provide an up2date 4.6.0 bundle image.
 
/cc @alanconway 
/assign @jcantrill 
 
### Links
- Depending on PR(s):  #720
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1884275

### CODE REVIEW

**Review by alanconway — CHANGES_REQUESTED** [review]
I think all these changes were in the final PR, maybe this is from an earlier version? Rebase & check if there's still anything missing.

**Comment by periklis** [comment]
@jcantrill PTAL, the bundle files are still not up2date.

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
