### PR TITLE
LOG-3497: Generate vector config for Detect Multiline Exceptions

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
This PR adds support for generating vector config for detecting and handling multiline exceptions. This requires a new transform for detecting and handling multiline exceptions., which is added in PR https://github.com/ViaQ/vector/pull/132

 - Enabled Multiline Exception functional test for vector
  
/cc 
/assign 

/cherry-pick 

### Links

- JIRA: https://issues.redhat.com/browse/LOG-3497

### CODE REVIEW

**Comment by jcantrill** [comment]
@vimalk78 leaving on hold for QE  to do testing before mreging

**Comment by vimalk78** [comment]
> @vimalk78 leaving on hold for QE to do testing before mreging

QE built from PRs and verified to be ok

**Pull request merged**
