### PR TITLE
Bug 1717627: Update replacement search text to match csv name in art.yaml

### PR DESCRIPTION
**Pull request by shawn-hurley**
Need to update the CSV name in the art.yaml file to match the actual name in the package file and the CSV name.

### CODE REVIEW

**Comment by bparees** [comment]
@eparis please cherry pick approve this so we can unblock our ART pipeline.

**Comment by bparees** [comment]
@jcantrill @ewolinetz this file also needs to exist in the master branch

**Comment by eparis** [comment]
show me the 4.2 PR is on track at the same time, and lets get someone in ART to ACK this please.

**Comment by bparees** [comment]
> show me the 4.2 PR is on track at the same time, and lets get someone in ART to ACK this please.

@adammhaile @sosiouxme can one of you ack this change?

**Comment by bparees** [comment]
@eparis @ewolinetz i've created the master PR here: https://github.com/openshift/cluster-logging-operator/pull/204

**Pull request merged**
