### PR TITLE
LOG-1400: elasticsearch output should add app- prefix to index names

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
This is an attempt to fix implementation of json log forwarding based on updated enhancement proposal.

/cc @jcantrill @alanconway 
/assign @jcantrill 

/cherry-pick 

### Links
- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal: PR https://github.com/openshift/enhancements/pull/780

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
/hold

@vimalk78 is this contingent upon merging the es plugin code?

**Comment by vimalk78** [comment]
yes @jcantrill

**Pull request merged**
