### PR TITLE
Bug 1884503: Updated Azure/go-autorest version

### PR DESCRIPTION
**Pull request by sasagarw**
### Description
This PR:
- updates the Azure/go-autorest to latest version.
- removes the jwt-go: access restriction bypass vulnerability.

/cc @vimalk78 
/assign @jcantrill 

/cherry-pick 

### Links
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1884503

### CODE REVIEW

**Comment by jcantrill** [comment]
/approve

I generally approve this but would only expect changes to `go.mod` and `go.sum` and probably those in `vendor`

**Review by vimalk78 — CHANGES_REQUESTED** [review]
please remove `main` and `output`

**Pull request merged**
