### PR TITLE
LOG-965: remove username and password from fluentd conf

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### Description

Remove from configuration default username and password

/cc 
/assign  @jcantrill 

/cherry-pick 

### Links

- JIRA: https://issues.redhat.com/browse/LOG-965

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Pull request merged**
