### PR TITLE
Correctly fixing the hack/registry.sh

### PR DESCRIPTION
**Pull request by vimalk78**
### Description
Avoid the `hack/registry.sh` script in CI.
change the CI environment variable check in script.

/cc 
/assign 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:

### CODE REVIEW

**Review by vparfonov — COMMENTED** [review]
Maybe here need to `exit 0`?

**Comment by vimalk78** [comment]
closing in favour of https://github.com/openshift/cluster-logging-operator/pull/1088

**Pull request closed without merging**
