### PR TITLE
Bug 1866531: Deploy source container template if infrastructire logs are forwarded

### PR DESCRIPTION
**Pull request by vimalk78**
Generated `source` to scrape container logs if "infrastructure" logs are forwarded
Modified test case

### CODE REVIEW

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
This does not address my suggestion which was to scrape infra and app logs separately with multiple source blocks differentiated by include excludes which either you gather logs or you do not:

Infra source:
```
path: /var/log/containers/*_openshift*_*.log, /var/log/containers/*_kube*_*.log, /var/log/containers/*_default_*.log
exclude_path: /var/log/containers/fluentd*_openshift-*_*.log, /var/log/containers/elasticsearch*_openshift*_*.log,/var/log/containers/kibana*_openshift*_*.log
```
App source:
```
path: /var/log/containers/*.log
exclude_path: /var/log/containers/*_openshift*_*.log, /var/log/containers/*_kube*_*.log, /var/log/containers/*_default_*.log
```
This would mean those logs get completely dropped from processing so as not to add to laod

**Comment by vimalk78** [comment]
> This does not address my suggestion which was to scrape infra and app logs separately with multiple source blocks differentiated by include excludes which either you gather logs or you do not:
> 
> Infra source:
> 
> ```
> path: /var/log/containers/*_openshift*_*.log, /var/log/containers/*_kube*_*.log, /var/log/containers/*_default_*.log
> exclude_path: /var/log/containers/fluentd*_openshift-*_*.log, /var/log/containers/elasticsearch*_openshift*_*.log,/var/log/containers/kibana*_openshift*_*.log
> ```
> 
> App source:
> 
> ```
> path: /var/log/containers/*.log
> exclude_path: /var/log/containers/*_openshift*_*.log, /var/log/containers/*_kube*_*.log, /var/log/containers/*_default_*.log
> ```
> 
> This would mean those logs get completely dropped from processing so as not to add to laod

@jcantrill why do want to associate source with app or infra? since we are differentiating them later in the fluent pipeline.

**Comment by jcantrill** [comment]
Had larger discussion where we should actually look for any infrastructure in the pipelines and exclude if=0.  That's a perf optimization we are foregoing now.

/approve
/hold cancel

**Comment by vimalk78** [comment]
similar discussion in earlier PR:
https://github.com/openshift/cluster-logging-operator/pull/649#discussion_r471343580

**Pull request merged**
