### PR TITLE
Operator status work

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
Example output:
```
status:
  collection:
    fluentdStatus:
      daemonSet: fluentd
      pods:
        fluentd-vb9h2: ip-172-18-3-167.ec2.internal
    normalizerStatus: {}
  curation:
    curatorStatus:
    - cronJobs: curator
      schedules: 30 3 * * *
      suspended: false
  logStore:
    elasticsearchStatus:
    - clusterName: elasticsearch
      deployments:
      - elasticsearch-clientdatamaster-0-1
      pods:
      - elasticsearch-clientdatamaster-0-1-555687575-ss2p2
      replicaSets:
      - elasticsearch-clientdatamaster-0-1-555687575
      replicas: 1
      statefulSets:
      - ""
  visualization:
    kibanaStatus:
    - deployment: kibana
      pods:
      - kibana-57f79f6b64-s8vgr
      replicaSets:
      - kibana-57f79f6b64
      replicas: 1
```

**Comment by josefkarasek** [comment]
Did you run `operator-sdk generate k8s`?

I can get es status but no else.

E.g. kibana status is:
```
v1alpha1.VisualizationSpec{Type: "",
    KibanaSpec:v1alpha1.KibanaSpec: {
        Resources:v1.ResourceRequirements: {
            Limits:v1.ResourceList(nil),
            Requests:v1.ResourceList(nil)
        },
        NodeSelector:map[string]string(nil),
        Replicas: 0,
        ProxySpec:v1alpha1.ProxySpec {
            Resources:v1.ResourceRequirements {
                Limits:v1.ResourceList(nil),
                Requests:v1.ResourceList(nil)
            }
        }
    }
}
```

**Comment by josefkarasek** [comment]
I hit this error today. Don't know more about it yet
```
INFO[1033] Updating status of Elasticsearch             
FATA[1033] Failed to update Cluster Logging status: Operation cannot be fulfilled on clusterloggings.logging.openshift.io "example": StorageError: invalid object, Code: 4, Key: /kubernetes.io/logging.openshift.io/clusterloggings/openshift-logging/example, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: de07b2c9-cc69-11e8-ba60-0eef3e96b418, UID in object meta:  
exit status 1
```

**Comment by ewolinetz** [comment]
@josefkarasek I've hit different errors on the update of Cluster Logging status. Once when I deleted the CR while the operator was running. I think there needs to be better error handling added around the `sdk.Update(status)` line.

**Pull request merged**
