### PR TITLE
Initial architecture page.

### PR DESCRIPTION
**Pull request by alanconway**
* High-level overview of the cluster logging architecture.
* Summary of work in progress on the design of future enhancments.
* Links to further details.

The idea is to keep this up to date with the source code, and fill it out over
time, to provide an accurate "big picture". This is _not_ intended to duplicate
information from JIRAs, enhancment requests, user documentation, or the source
code itself. It is intended to make it easier to understand the project as a
whole and to provide links to help find the details you need.

### CODE REVIEW

**Comment by alanconway** [comment]
/uncc @periklis 
/uncc @igor-karpukhin 

@jcantrill can you LGTM this? Once the initial draft is in I can figure out how best to host the permanent web-page (currently the pretty version is in my personal github.io) and will start making regular updates.

**Comment by alanconway** [comment]
/cc @jcantrill 
Can I have an LGTM?

**Review by periklis — COMMENTED** [review]
/lgtm

**Comment by alanconway** [comment]
Moved to master-post-release. @jcantrill  new LGTM please.

**Pull request merged**
