### PR TITLE
remove release operator label

### PR DESCRIPTION
**Pull request by jcantrill**
This PR removes the CLO from the CVO build pipeline

cc @bparees

### CODE REVIEW

**Comment by ewolinetz** [comment]
based on slack discussions, lgtm. I think we need to switch this to another one though

**Comment by jcantrill** [comment]
> based on slack discussions, lgtm. I think we need to switch this to another one though

What do you mean? This PR just removes us from the CVO pipeline and https://github.com/openshift/cluster-logging-operator/pull/113 will at some point add us to the RH operator hub pipeline

**Comment by ewolinetz** [comment]
I was referring to `com.redhat.delivery.appregistry=true`

**Pull request merged**
