### PR TITLE
Fix Makefile dependency problems

### PR DESCRIPTION
**Pull request by alanconway**
Fix Makefile dependency problems

- check in .bingo/*.sum files, otherwise CI fails trying to create them.
- pre-submit target: ensure generated stuff up-to-date before submitting PR
- make check the default target
- update docs/HACKING.md to be consistent.

### CODE REVIEW

**Comment by alanconway** [comment]
@jcantril need another /lgtm, rebased.

**Comment by alanconway** [comment]
@jcantril another LGTM please.

**Comment by jupierce** [comment]
Per Jeff, blocked by https://github.com/openshift/cluster-logging-operator/pull/657

**Pull request merged**
