### PR TITLE
Bug 1706134: Allowing scale up past 3 nodes for ES Cr 

### PR DESCRIPTION
**Pull request by ewolinetz**
Alternative fix vs https://github.com/openshift/cluster-logging-operator/pull/168

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1706134

### CODE REVIEW

**Comment by josefkarasek** [comment]
Looking good, @ewolinetz.

For future plans @lukas-vlcek and I have tried to come up with possible topologies based on number of nodes:
```
1 - 3:  _i_ CDM
4 - 9: 3 CDM + _i_ - 3 CD
10 and more: 3 M + 3 C + _i_ - 6 D
```

> _i_ = nodeCount

**Comment by jcantrill** [comment]
Please remove the role names from the artifacts as this will affect migrating to topolgies > 3

**Comment by ewolinetz** [comment]
@jcantrill i need to make those changes in EO, i'll open a pr to address that as part of this fix

**Pull request merged**
