### PR TITLE
Bug 1925361: fix routing of app logs per namespace

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR
* fixes routing of application messages by namespace so they end up at the desired outputs

/cc @alanconway @vimalk78 

### Links
* https://bugzilla.redhat.com/show_bug.cgi?id=1925361
* https://bugzilla.redhat.com/show_bug.cgi?id=1905615
backport of 5.0 https://github.com/openshift/cluster-logging-operator/pull/976

### CODE REVIEW

**Comment by jcantrill** [comment]
labeling as valid since it properly targets 4.6.z.   Need an update to the bot to correct.

**Review by vimalk78 — APPROVED** [review]
/lgtm

**Comment by droslean** [comment]
@jcantrill The plugin is correct. See your configuration [here](https://github.com/openshift/release/blob/9b3a2a960f04d81f9549381298dbd71194e9d992/core-services/prow/02_config/_plugins.yaml#L625-L630).

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.30

**Pull request merged**
