### PR TITLE
Bug 1882524: removed logforwardings.crd.yaml from manifest/4.6

### PR DESCRIPTION
**Pull request by vimalk78**
The CVP test case 
one of the test cases is failed for this image https://pipeline.engineering.redhat.com/test-results/containerkojibuild/cluster-logging-operator-metadata-container-v4.6.0.202009281851.p0-1
```
time="2020-09-28T19:19:51Z" level=error msg="Error: Value logging.openshift.io/v1alpha1, Kind=LogForwarding: CRD \"logging.openshift.io/v1alpha1, Kind=LogForwarding\" is present in bundle \"clusterlogging.4.6.0-202009281851.p0\" but not defined in CSV"
```

This PR removes logforwardings.crd.yaml from from manifest/4.6 folder

/cc @igor-karpukhin 
/cc @syedriko 
/assign @jcantrill

### CODE REVIEW

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Comment by bparees** [comment]
closed in deference to https://github.com/openshift/cluster-logging-operator/pull/717

/close

**Pull request closed without merging**
