### PR TITLE
updating dns name generation for certs and updating hash alg

### PR DESCRIPTION
**Pull request by ewolinetz**
addresses https://bugzilla.redhat.com/show_bug.cgi?id=1684332 issue for 4.0

### CODE REVIEW

**Comment by richm** [comment]
Is `sha256` the best current choice for signature algorithm?

**Comment by ewolinetz** [comment]
@richm we could use sha512 ...

**Comment by ewolinetz** [comment]
@jcantrill i think we would need to make a similar change for ansible where we change the md value in the signing confs

**Pull request merged**
