### PR TITLE
Minor fixes to tech-preview branch.

### PR DESCRIPTION
**Pull request by alanconway**
- make unit-test: was not running unit tests under test/
- fix minor unit test failures
- make undeploy:  wait for delete to complete, avoid create races.
- make lint: fix errors.
- go mod tidy
- Test helper func GitRoot to find root of current git repo.

/assign @jcantrill

### CODE REVIEW

**Comment by alanconway** [comment]
@jcantrill need new LGTM, the test/client also needs to be excluded from unit tests. This time ran locally with CRC off to verify so should be good.

**Review by periklis — APPROVED** [review]
/lgtm

**Comment by alanconway** [comment]
++













Closing, will get TP branch up to speed with master and get it passing CI first.

**Pull request closed without merging**
