### PR TITLE
Master into postrelease

### PR DESCRIPTION
**Pull request by jcantrill**
### Description

Update master-post-release to latest master

cc @vimalk78

### CODE REVIEW

**Comment by alanconway** [comment]
Do we need postrelease any more? If we use a release-5.0 branch for the release shut-down, then we can keep using master for 5.1 development.

**Comment by jcantrill** [comment]
> Do we need postrelease any more? If we use a release-5.0 branch for the release shut-down, then we can keep using master for 5.1 development.

@alanconway we likely do not, but we do need at least one last merge of master into this and this back to master as this branch has some changes we landed for 5.1

**Comment by jcantrill** [comment]
overriding test as its a failure in eventrouter that is fixed on master

**Comment by jcantrill** [comment]
manually merging to get back into master

**Pull request merged**
