### PR TITLE
Bug 1619479: Remove Kibana oauth-proxy param to allow re-login

### PR DESCRIPTION
**Pull request by jcantrill**
Remove parameter so Kibana re-login does not redirect more then once.

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1619479

### CODE REVIEW

**Comment by ewolinetz** [comment]
@jcantrill after your discussion with @bparees is this still the correct fix for the linked bz?

**Comment by bparees** [comment]
@ewolinetz this PR was the outcome of our discussion/investigation of that BZ

**Pull request merged**
