### PR TITLE
DO NOT MERGE: Test for 'empty config with namespaces'

### PR DESCRIPTION
**Pull request by alanconway**
According to https://bugzilla.redhat.com/show_bug.cgi?id=1857673 we generate an empty fluentd config if the 'namespaces' feature is used.  This unit test shows that the generator works correctly with the suspect YAML file, so we must be dropping the configuration somewhere else.

/hold
DO NOT MERGE - @vimalk78 owns this and will merge the final result, this is just a temporary work area.

### CODE REVIEW

**Comment by alanconway** [comment]
@vimalk78 do you still need this PR? If not I'll close it.

**Comment by vimalk78** [comment]
@alanconway you can close it

**Comment by alanconway** [comment]
Has been included in #626

**Pull request closed without merging**
