### PR TITLE
Fix typo: fluend -> fluentd

### PR DESCRIPTION
**Pull request by ahadas**

### CODE REVIEW

**Comment by jparrill** [comment]
Hey @ahadas do you have an Issue to see the error that you receives? I mean, I'm dealing with a FluentD error (the pods are in CrashLoopBackOff but I have not any relevant logs) and it's not easy to do the blind debugging... :)

**Comment by ahadas** [comment]
> Hey @ahadas do you have an Issue to see the error that you receives? I mean, I'm dealing with a FluentD error (the pods are in CrashLoopBackOff but I have not any relevant logs) and it's not easy to do the blind debugging... :)

Hi @jparrill , unrelated to this PR, right? So fluentd crashes and along with it the container so you have no access to the logs, do I understand it right? if so, maybe you can override the container's entrypoint (by setting Args/Command on the container) and then log in to the container (oc rsh ...) and attempt to start it manually?

**Comment by jparrill** [comment]
> > Hey @ahadas do you have an Issue to see the error that you receives? I mean, I'm dealing with a FluentD error (the pods are in CrashLoopBackOff but I have not any relevant logs) and it's not easy to do the blind debugging... :)
> 
> Hi @jparrill , unrelated to this PR, right? So fluentd crashes and along with it the container so you have no access to the logs, do I understand it right? if so, maybe you can override the container's entrypoint (by setting Args/Command on the container) and then log in to the container (oc rsh ...) and attempt to start fluentd it manually?

I've created this Issue, seems that is not related with this one: https://github.com/openshift/cluster-logging-operator/issues/347 

btw thanks for your fast response ;)

**Pull request merged**
