### PR TITLE
[release-5.9] LOG-6044: Multi CLF validation failure when adding a namespace which contains "kube" or "openshift"

### PR DESCRIPTION
**Pull request by Clee2691**
### Description
This PR reverts https://github.com/openshift/cluster-logging-operator/pull/2794 validation of infrastructure namespaces.

This PR also defines the below infrastructure namespaces that are to be included when the infrastructure input is defined. It also adjusts the excluded list by adding the below infrastructure namespaces to exclude for application input sources. It is a manual port of: https://github.com/openshift/cluster-logging-operator/pull/2871

The infrastructure namespaces are as 
1. `default`
2. `openshift`
3. Any namespace prefixed with `openshift-`
4. `kube`
5. Any namespace prefixed with `kube-`

/cc @cahartma @vparfonov 
/assign @jcantrill 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-6044

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm

**Review by cahartma — COMMENTED** [review]
/lgtm

**Pull request merged**
