### PR TITLE
modify kafka e2e test to assume success if source type is ever found

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR modifies the kafka e2e test:
* To skip checking source types on polling if found at least onece

### CODE REVIEW

**Comment by jcantrill** [comment]
cc @syedriko

**Review by syedriko — COMMENTED** [review]
DefaultWaitForLogsTimeout is 10 minutes, PollImmediate() with it's 5 minutes can give up before that. May be a better way to express this is along these lines:
```
var wg sync.WaitGroup
funcs := []func(){
	func() {
		defer wg.Done()
		hasAppLogs, err = e2e.LogStores[app.Name].HasApplicationLogs(helpers.DefaultWaitForLogsTimeout)
		if err != nil {
			log.Error(err, "Error trying to get app logs")
		}
	},
	func() {
		defer wg.Done()
		hasInfraLogs, err = e2e.LogStores[app.Name].HasInfraStructureLogs(helpers.DefaultWaitForLogsTimeout)
		if err != nil {
			log.Error(err, "Error trying to get infra logs")
		}
	},
	func() {
		defer wg.Done()
		hasAuditLogs, err = e2e.LogStores[app.Name].HasAuditLogs(helpers.DefaultWaitForLogsTimeout)
		if err != nil {
			log.Error(err, "Error trying to get audit logs")
		}
	},
}
wg.Add(len(funcs))
for _, f := range funcs {
	go f()
}
wg.Wait()
```

**Comment by jcantrill** [comment]
@syedriko updated per your suggestions

**Comment by jcantrill** [comment]
Closing as we believe CW pr resolves issues related to the kafka test

**Pull request closed without merging**
