### PR TITLE
Bug 1808167: Update crypto dependency

### PR DESCRIPTION
**Pull request by jcantrill**
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1808167

### CODE REVIEW

**Comment by syedriko** [comment]
@jcantrill How can I tell if the updated golang.org/x/crypto fixes the CVE?

**Comment by jcantrill** [comment]
> Looks we miss the `Gopkg.toml` or did this not require an update?

I did not see a diff for it but I was surprised it wasn't their either

**Comment by periklis** [comment]
> > Looks we miss the `Gopkg.toml` or did this not require an update?
> 
> I did not see a diff for it but I was surprised it wasn't their either

Then it is an indirect dependency.

/lgtm

**Pull request merged**
