### PR TITLE
LOG-4383: resolve conflict between outputs and pipelines name

### PR DESCRIPTION
**Pull request by vparfonov**
### Description
This PR addresses the issue where conflicts between output and pipeline names have been occurring due to label generation. The root cause of this problem is that FluentD requires labels to be unique. We will prefix the label with 'OUTPUT_' for labels which conflict with pipeline names. This adjustment ensures that output labels are unique and distinct from pipeline names.

/cc 
/assign @jcantrill 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-4383
- Enhancement proposal:

### CODE REVIEW

**Comment by jcantrill** [comment]
@vparfonov please add a functional test to verify this behavior

**Comment by vparfonov** [comment]
> @vparfonov please add a functional test to verify this behavior

@jcantrill https://github.com/openshift/cluster-logging-operator/pull/2186/files#diff-bd1d4fee56357dfab1ba610e3afd01969551e738ed9a524845df68c4ae691f00R71

**Pull request merged**
