### PR TITLE
updating to use a single collector SA

### PR DESCRIPTION
**Pull request by ewolinetz**
Part of fix for https://bugzilla.redhat.com/show_bug.cgi?id=1672772

### CODE REVIEW

**Comment by jcantrill** [comment]
holding until https://github.com/openshift/elasticsearch-operator/pull/71 merges.  I'm not certain if the success of `e2e-operator` properly captures the changes

**Comment by ewolinetz** [comment]
wouldn't this be dependent on the CLO e2e test, not the EO ones?

**Comment by jcantrill** [comment]
> wouldn't this be dependent on the CLO e2e test, not the EO ones?

agreed.

**Pull request merged**
