### PR TITLE
Code cleanup. Make lint target a prerequisite to build

### PR DESCRIPTION
**Pull request by igor-karpukhin**
Changelist:
* Code cleanup
    * Removed unused entities
    * Fixed missing error handlers
* `golangci-lint` is a mandatory target to run for `make build`

### CODE REVIEW

**Comment by periklis** [comment]
@igor-karpukhin AFAIK we dropped generate in #436 to fix ART builds. Will this not re-introduce this blocker again? IMHO, the dev targets that depend on downloading binaries won't work with ART.

**Comment by igor-karpukhin** [comment]
@periklis I opened this PR before your message in slack about ART builds. I'll remove the `lint` dependency.

**Comment by periklis** [comment]
@igor-karpukhin We can close this in favor of #617, don't you think?

**Comment by alanconway** [comment]
@igor-karpukhin please close this, it's been fixed by  #617

**Pull request closed without merging**
