### PR TITLE
GitHub bug issue template

### PR DESCRIPTION
**Pull request by syedriko**
A template for GitHub issues opened against this repo

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve

**Comment by jcantrill** [comment]
@alanconway @ewolinetz thoughts?  any other needs

**Review by alanconway — APPROVED** [review]
/lgtm

**Comment by ewolinetz** [comment]
/lgtm
@syedriko would you mind creating this for our other repos as well?

**Comment by syedriko** [comment]
> /lgtm
> @syedriko would you mind creating this for our other repos as well?

Not at all, it's been the plan to clone this one once we've settled on what we want in it. This one has got enough ltgms.

**Pull request merged**
