### PR TITLE
Script fixes

### PR DESCRIPTION
**Pull request by jamezp**
A couple fixes found in #119 for the scripts.

### CODE REVIEW

**Comment by ewolinetz** [comment]
I'm good with using the vendored in elasticsearch-operator. 
Can you explain why we're removing a script from the vendored directory though?

**Comment by jamezp** [comment]
@ewolinetz It's just removing the processing of the `vendor/github.com/coreos/prometheus-operator/example/prometheus-operator-crd` directory as that directory doesn't exist. It's possible the correct solution is to add the directory, but I'm not sure what should go in there.

**Comment by ewolinetz** [comment]
ack, I didn't expand that diff to see that. The only major concern I have with that is when we do a `dep ensure -update` we'll lose that change so it seems very fragile to me.

Also, without those files the Elasticsearch operator will have errors in it

**Comment by richm** [comment]
The problem is that these scripts/Makefiles were written with developers in mind, and with those developers being both elasticsearch-operator and cluster-logging-operator developers at the same time, and who have both elasticsearch-operator and cluster-logging-operator checked out at the same level under ~/go/src/github.com/openshift (or whatever the GOPATH is) - not sure how to rewrite the scripts to give developers the ability to use either `../elasticsearch-operator` or `vendor/..../elasticsearch-operator`

**Comment by jamezp** [comment]
Ah okay. This PR definitely could be wrong for sure. I was just attempting the [quick start example](https://github.com/openshift/cluster-logging-operator#quick-start). It's definitely possible I don't have the environment setup correct.

if this is wrong too feel free to close. I doesn't look like I'll be able to use this OpenShift 3.x anyway. I was just hoping to so I could test some WildFly/JBoss EAP logging changes that are coming in :)

**Comment by jcantrill** [comment]
Closing Per @richm comment.  These are intended for use by dev

**Pull request closed without merging**
