### PR TITLE
Post release into master

### PR DESCRIPTION
**Pull request by jcantrill**
merge post release back into master for 4.2

### CODE REVIEW

**Comment by nhosoi** [comment]
Now we need the prometheusrules role?
```
--- FAIL: TestClusterLogging (518.75s)
    --- FAIL: TestClusterLogging/collectors (120.00s)
        --- FAIL: TestClusterLogging/collectors/fluentd (205.99s)
        	clusterlogging_test.go:158: Initializing cluster resources...
```

**Comment by richm** [comment]
Do we need to add the prometheusrules rbac or some other rbac before e2e-operator will pass?

**Comment by jcantrill** [comment]
> Do we need to add the prometheusrules rbac or some other rbac before e2e-operator will pass?

Possibly but I defer to @ewolinetz and @josefkarasek .  I was hopen it was a simple merge

**Comment by nhosoi** [comment]
> > Do we need to add the prometheusrules rbac or some other rbac before e2e-operator will pass?
> 
> Possibly but I defer to @ewolinetz and @josefkarasek . I was hopen it was a simple merge

https://github.com/openshift/cluster-logging-operator/pull/177 shares the same issue...
@josefkarasek, following your advice, this PR https://github.com/operator-framework/community-operators/pull/304 had been merged some time back (about 2 weeks ago).  It seems this was not enough for the CI tests' passing...?

**Comment by ewolinetz** [comment]
We need to actually update the csv to add `- prometheusrules` since it doesn't appear to be on this pr. I think for the time being we can just update the v4.1.0 one and then create a 4.2.0 as a follow up PR

**Comment by ewolinetz** [comment]
we are also missing other changes that were made to the CSV that is required for the CLO (with the sdk bump) to deploy. possibly e2e test changes too

**Pull request merged**
