### PR TITLE
LOG-1738: fluentd total_limit_size sets value beyond available space

### PR DESCRIPTION
**Pull request by ajaygupta978**
Description
This PR fixes buffer memory size issue.

/cc @jcantrill
/cc @vimalk78
/assign @jcantrill

/cherry-pick

Links
Depending on PR(s):
Bugzilla:
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-1738
Enhancement proposal:

### CODE REVIEW

**Comment by ajaygupta978** [comment]
**Before Fix**

Default
--------------------
```
# oc logs  -c fluentd   fluentd-kcxpf
Setting each total_size_limit for 3 buffers to 6415029657 bytes
Setting queued_chunks_limit_size for each buffer to 764
Setting chunk_limit_size for each buffer to 8388608
```
change total_limit_size to 100G
--------------------
```
# oc logs fluentd-2zwx9 -c fluentd
Setting each total_size_limit for 3 buffers to 107374182400 bytes
Setting queued_chunks_limit_size for each buffer to 12800
Setting chunk_limit_size for each buffer to 8388608
```
**After Fix**
--------------------
```
# oc logs fluentd-889fm -c fluentd 
Requested buffer size per output 107374182400 for 3 buffers exceeds maximum available size  6415029657 bytes per output
Setting each total_size_limit for 3 buffers to 6415029657 bytes
Setting queued_chunks_limit_size for each buffer to 764
Setting chunk_limit_size for each buffer to 8388608
```

**Comment by jcantrill** [comment]
@ajaygupta978 please title the PR and commit in the form of "LOG-XXXXX:  Description of solution"

**Review by jcantrill — COMMENTED** [review]
/lgtm

**Pull request merged**
