### PR TITLE
LOG-1736:fluentd total_limit_size wrong values echoed

### PR DESCRIPTION
**Pull request by ajaygupta978**
This PR fixes buffer memory size issue.

/cc @jcantrill
/cc @vimalk78
/assign @jcantrill

/cherry-pick

Links
Depending on PR(s):
Bugzilla: 
Github issue:
JIRA: https://issues.redhat.com/browse/LOG-1736
Enhancement proposal:

### CODE REVIEW

**Comment by ajaygupta978** [comment]
Default output
```
Setting each total_size_limit for 2 buffers to 9622544486 bytes
Setting queued_chunks_limit_size for each buffer to 1147
Setting chunk_limit_size for each buffer to 8388608
```
After changing totalLimitSize to 8G

```
Setting each total_size_limit for 2 buffers to 8589934592 bytes
Setting queued_chunks_limit_size for each buffer to 1024
Setting chunk_limit_size for each buffer to 8388608
```
After changing totalLimitSize to 18G
```
Requested buffer size per output 19327352832 for 2 buffers exceeds maximum available size  9622544486 bytes per output
Setting each total_size_limit for 2 buffers to 9622544486 bytes
Setting queued_chunks_limit_size for each buffer to 1147
Setting chunk_limit_size for each buffer to 8388608
```

**Comment by ajaygupta978** [comment]
@jcantrill: I have linked Jira ticket. Hope we don't need to create any Buzilla bug. Please review.

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
