### PR TITLE
LOG-2405: Move kafka e2e tests to functional

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR addresses flakes in kafka testing:
* Backports restructing of framework package code. Ref: https://github.com/openshift/cluster-logging-operator/pull/1213
* Moves kafka e2e test to functional test: Ref: https://github.com/openshift/cluster-logging-operator/pull/1369
* Blocks any 1.7.4 fluentd PRs that consistently are blocked on forward testing for release-5.2
* This PR also backports  input_selector_test

cc @alanconway @syedriko 

Note:  Intentionally left as two commits to separate framework package work from test changes
### Links
* https://issues.redhat.com/browse/LOG-2405
* https://issues.redhat.com/browse/LOG-2435

### CODE REVIEW

**Review by alanconway — APPROVED** [review]
/lgtm

**Review by syedriko — CHANGES_REQUESTED** [review]

**Pull request merged**
