### PR TITLE
LOG-2622: update golang to v1.17

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR:
* Updates golang v1.17 to unblock https://issues.redhat.com/browse/LOG-2522

### Links
* https://issues.redhat.com/browse/LOG-2622

### CODE REVIEW

**Comment by xperimental** [comment]
Sorry for the hold, but Go 1.17 changes the way the `go.mod`/`go.sum` files look a bit. I think it makes sense to run `go mod tidy -go 1.17` in the repo, so that these changes are contained in this PR and not occur when the next dependency change happens. Unless there will still be builds happening with Go 1.16.

**Review by alanconway — APPROVED** [review]
/lgtm

**Pull request merged**
