### PR TITLE
Bug 1930961: Use viaq logerr to simplify backports to 4.6

### PR DESCRIPTION
**Pull request by jcantrill**
### Description
This PR makes the log library consistent with post 4.6 to clean up logging and facilitate backport changes

cc @alanconway @vimalk78 

https://bugzilla.redhat.com/show_bug.cgi?id=1930961
5.0 change as part of [LOG-745](https://issues.redhat.com/browse/LOG-745) in https://github.com/openshift/cluster-logging-operator/pull/704

### CODE REVIEW

**Review by igor-karpukhin — APPROVED** [review]
/lgtm

**Comment by jcantrill** [comment]
placed on hold pending consensus?

**Comment by jcantrill** [comment]
/hold cancel

ref https://coreos.slack.com/archives/GGUR75P60/p1614093050083400

**Comment by jcantrill** [comment]
/label bugzilla/vaild

This change already exists in later release as noted by original comment

**Pull request merged**
