### PR TITLE
Force all CL components to be allocated to linux nodes

### PR DESCRIPTION
**Pull request by lukas-vlcek**
See [LOG-411](https://jira.coreos.com/browse/LOG-411)

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
My first PR to CLO. I still need to figure out if tests are passing... bear with me.

**Comment by jcantrill** [comment]
> Are we only going to support our components running on Linux for the time being?
> Is there a reason to create non-linux node selectors?

Right now we only support running on linux

**Comment by lukas-vlcek** [comment]
@jcantrill If we are sure we are going to support only linux nodes going forward then we do not need to introduce a new function and just bake the linux selector into original `func NewPodSpec` instead (and properly document this aspect of it).
Is this what you would prefer more?

**Comment by ewolinetz** [comment]
>If we are sure we are going to support only linux nodes going forward then we do not need to introduce a new function and just bake the linux selector into original func NewPodSpec instead (and properly document this aspect of it).
Is this what you would prefer more?

I would prefer that we just add the selector into the original function, that was why I was asking if we were going to support non-linux installations.

**Comment by jcantrill** [comment]
> @jcantrill If we are sure we are going to support only linux nodes going forward then we do not need to introduce a new function and just bake the linux selector into original `func NewPodSpec` instead (and properly document this aspect of it).
> Is this what you would prefer more?

I concur with @ewolinetz to reusing the existing function.  The only component I anticipate living on a non-linux node is the collector which we need to make several other adjustments to support anyway.

**Comment by lukas-vlcek** [comment]
Closing in favour of https://github.com/openshift/cluster-logging-operator/pull/191

**Comment by lukas-vlcek** [comment]
@jcantrill @ewolinetz I did requested changes and created new PR to drive it from my fork instead of branch in upstream.

**Pull request closed without merging**
